id: P006865
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 12:27:24.378517
source_metadata:
  id: bdr:W21971
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ།
  author: ''
  organization: https://bdrc.io
  volumes:
    1c8287928fa04baeae80c53f63310577:
      image_group_id: I1KG8809
      title: ''
      volume_number: 1
      total_pages: 141
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
