id: P006865
initial_creation_type: ocr
created_date: 27/03/2020
updated_date: 21/06/2021
source_metadata:
  id: bdr:W21971
  title: བྱང་ཆུབ་སེམས་དཔའི་སྤྱོད་པ་ལ་འཇུག་པ།
  author: ''
  volumes:
    1c8287928fa04baeae80c53f63310577:
      image_group_id: I1KG8809
      title: ''
      volume_number: 1
      total_pages: 141
      base_file: v001.txt
